name: Citizens
authors: [aPunch, fullwall]
softdepend: [Vault]
version: ${project.version} (build ${BUILD_NUMBER})
main: net.citizensnpcs.Citizens
website: http://www.citizensnpcs.com
commands:
  traitc:
    aliases: [trc, tc]
    description: Configures traits
  trait:
    aliases: [tr]
    description: Trait commands
  script:
    aliases: [sc]
    description: Scripting commands
  citizens:
    aliases: [citizens2]
    description: Administration commands
  npc:
    aliases: [npc2]
    description: Basic commands for all NPC-related things
  template:
    aliases: [tpl]
    description: Template commands
  waypoint:
    aliases: [waypoints, wp]
    description: Waypoint commands
permissions:
  citizens.*:
    default: op
    children:
      citizens.admin.*:
        children:
            citizens.admin: true
            citizens.admin.avoid-limits: true
            citizens.admin.remove.all: true
      citizens.help.*:
        children:
            citizens.npc.help: true
            citizens.trait.help: true
            citizens.help: true
            citizens.waypoints.help: true
            citizens.templates.help: true
            citizens.citizens.help: true
            citizens.script.help: true
      citizens.script.*:
        children:
            citizens.script.compile: true
            citizens.script.help: true
      citizens.templates.*:
        children:
            citizens.templates.apply: true
            citizens.templates.create: true
      citizens.waypoints.*:
        children:
            citizens.waypoints.disableteleport: true
            citizens.waypoints.provider: true
      citizens.npc.*:
        children:
          citizens.npc.age: true
          citizens.npc.anchor: true
          citizens.npc.behaviour: true
          citizens.npc.controllable: true
          citizens.npc.copy: true
          citizens.npc.create: true
          citizens.npc.despawn: true
          citizens.npc.edit.*:
            children:
                citizens.npc.edit.equip: true
                citizens.npc.edit.path: true
                citizens.npc.edit.text: true
          citizens.npc.gravity: true
          citizens.npc.help: true
          citizens.npc.ignore-cost: true
          citizens.npc.list: true
          citizens.npc.lookclose: true
          citizens.npc.moveto: true
          citizens.npc.owner: true
          citizens.npc.path: true
          citizens.npc.pathfindingrange: true
          citizens.npc.pose: true
          citizens.npc.power: true
          citizens.npc.profession: true
          citizens.npc.remove: true
          citizens.npc.rename: true
          citizens.npc.select: true
          citizens.npc.size: true
          citizens.npc.skeletontype: true
          citizens.npc.spawn: true
          citizens.npc.speed: true
          citizens.npc.talk: true
          citizens.npc.text:
            children:
              citizens.npc.edit.text: true
          citizens.npc.tp: true
          citizens.npc.tphere: true
          citizens.npc.tpto: true
          citizens.npc.trait.*:
            children:
                citizens.npc.trait: true
                citizens.npc.trait-configure: true
          citizens.npc.vulnerable: true
          citizens.npc.wolf: true