name: Citizens
authors: [aPunch, fullwall]
version: 2.0
main: net.citizensnpcs.Citizens
website: http://www.citizensnpcs.net
commands:
  citizens:
    description: Administration commands
  npc:
    description: Basic commands for all NPC-related things
permissions:
  citizens.*:
    default: op
    children:
      citizens.admin: true
      citizens.help: true
      citizens.npc.*:
        children:
          citizens.npc.character.*: true
          citizens.npc.create: true
          citizens.npc.despawn: true
          citizens.npc.edit.*:
            children:
              citizens.npc.edit.equip: true
              citizens.npc.edit.path: true
              citizens.npc.edit.text: true
          citizens.npc.help: true
          citizens.npc.list: true
          citizens.npc.owner: true
          citizens.npc.power: true
          citizens.npc.remove: true
          citizens.npc.remove.all: true
          citizens.npc.rename: true
          citizens.npc.select: true
          citizens.npc.spawn: true
          citizens.npc.talk: true
          citizens.npc.tp: true
          citizens.npc.tphere: true
          citizens.npc.lookclose: true