name: Bug Report
description: Use this form to report a bug with Citizens.

body:
  - type: 'markdown'
    attributes:
      value: |-
        ## DO NOT IGNORE
        Please fill out all required fields the way they are described as.
        **Not following the issue form will get it closed automatically!**
        
        ### Section 1) Version Infos
        Include the outputs of `/version` and `/version Citizens` in the respective fields.
  - type: 'textarea'
    attributes:
      label: '`/version` output'
      description: 'Include the **complete** output of the `/version` command here.'
      placeholder: 'This server is running ...'
      render: txt
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: '`/version Citizens` output'
      description: 'Include the **complete** output of the `/version Citizens` command here.'
      placeholder: 'Citizens Version ...'
      render: txt
    validations:
      required: true
  - type: 'markdown'
    attributes:
      value: |-
        ### Section 2) Log and Configuration files
        Provide your server's latest log file and the configuration file (`config.yml`) of Citizens.
        
        When your problem is a Performance issue will you need to also include the `saves.yml` of Citizens.
  - type: 'input'
    attributes:
      label: 'Log file'
      description: 'Upload your server''s latest.log on pastebin or similar and share the URL.'
      placeholder: 'https://pastebin.com/...'
    validations:
      required: true
  - type: 'input'
    attributes:
      label: 'config.yml'
      description: 'Upload the config.yml of Citizens on pastebin or similar and share the URL.'
      placeholder: 'https://pastebin.com/...'
    validations:
      required: true
  - type: 'input'
    attributes:
      label: 'saves.yml'
      description: |-
        **ONLY REQUIRED FOR PERFOMANCE ISSUES!**
        Upload the saves.yml of Citizens on pastebin or similar and share the URL.'
      placeholder: 'https://pastebin.com/...'
  - type: 'markdown'
    attributes:
      value: |-
        ### Section 3) Performance Report
        **This section is only required when having Performance issues!**
        
        Include a report from a profiler such as Spark [[Download](https://spark.lucko.me/download)].
        Spigot Timings alone are NOT allowed, but can be included alongside another profiler report.
  - type: 'input'
    attributes:
      label: 'Profiler report'
      description: 'Post the Report from a profiler such as Spark here.'
      placeholder: 'https://spark.lucko.me/...'
  - type: 'markdown'
    attributes:
      value: |-
        ### Section 3) Information
        Give a detailed explanation about your current issue.
        When possible, include steps to redproduce it reliably.
  - type: 'textarea'
    attributes:
      label: 'Description'
      description: 'Give a detailed description of the issue you encounter.'
      placeholder: 'When doing ... does Citizens do ...'
    validations:
      required: true
