blank_issues_enabled: true
contact_links:
  - name: Wiki
    about: 'Please visit the Citizens Wiki before reporting issues.'
    url: 'https://wiki.citizensnpcs.co/Citizens_Wiki'
  - name: Citizens API
    about: 'Documentation about the API of Citizens.'
    url: 'https://wiki.citizensnpcs.co/API'
  - name: Development Builds
    about: 'Dev builds of Citizens. Always make backups before updating.'
    url: 'https://ci.citizensnpcs.co/job/Citizens2/'
  - name: Denizen and Citizens Discord
    about: 'Ask questions here!'
    url: 'https://discord.gg/Q6pZGSR'
